server:
  port: 60000
spring:
  cloud:
    config:
      server:
              # 配置文件放到服务端本地
        #native:
        #  search-locations: classpath:/config/
              # 配置文件放在GitHub
        git:
          uri: https://github.com/ruiruiya/springcloud-config-server.git
          #username: 
          #password: 